### ISSUE TITLE
Address pinned dependencies

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopop#104]
See [requirements.txt](https://github.com/uw-echospace/EchoPro/blob/master/requirements.txt) and [condaenvironment.yaml](https://github.com/uw-echospace/EchoPro/blob/master/condaenvironment.yaml), including the comments that point to some of the issues.

### General
- [ ] pandas<2
- [ ] shapely<2

### Jupyter
- [ ] ipywidgets<8
- [ ] notebook<6.5
- [ ] traitlets<5.10

**Comment by emiliom** [comment]
I'll investigate the current issues with pandas and shapely versions &ge; 2. At the very least, I'll document the errors or warnings that are occurring, and where they're happening.

**Comment by emiliom** [comment]
I created a an echopro development environment where I removed the pandas and shapely pinning, then did some testing.

- `shapely`: As far as I can see, the issue is gone! Whatever library that used shapely and had not been ported to shapely >= 2 is no longer an issue. **`shapely` pinning can be removed.**
- `pandas`: Pandas 2.1 doesn't cause failures, but it does generate the same type of warning in a few places (pasted below), involving `groupby`. From [what I've read, this warning is "un-actionable"](https://github.com/pandas-dev/pandas/issues/54775) -- there's nothing one can do to avoid it, until something changes in Pandas. Except possibly avoid the use of categorical data type. A related [Pandas PR fixed at least some aspect of this issue in August](https://github.com/pandas-dev/pandas/pull/54789) and went into Pandas 2.1, but the warning is still there. So: we can remove the pinning and live with the warning for the time being, or see if changing from the offending categorical data type to a different type eliminates the warning w/o causing problems.

```bash
/usr/mayorgadat/workmain/acoustics/gh/uw-echospace/EchoPro/EchoPro/computation/cv.py:78: 
  FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. 
  Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  transect_info["area"].groupby(strata_lat_stratum).agg(["count", "sum"])

/usr/mayorgadat/workmain/acoustics/gh/uw-echospace/EchoPro/EchoPro/computation/cv.py:182: 
  FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas.  
  Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  transect_info["area"].groupby(strata_lat_stratum).agg(["count", "sum"])

/usr/mayorgadat/workmain/acoustics/gh/uw-echospace/EchoPro/EchoPro/computation/length_age_variables.py:224: 
  FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. 
  Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  abundance_df.groupby(level=0).sum()[abundance_var_name].to_xarray()

/usr/mayorgadat/workmain/acoustics/gh/uw-echospace/EchoPro/EchoPro/computation/length_age_variables.py:318: 
  FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. 
  Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bio_times_area.set_index("stratum_num")
```

**Comment by brandynlucca** [comment]
The suite of dependencies required by `Echopop` has changed, so this Issue is no longer applicable. Therefore this can be closed.
