### ISSUE TITLE
Create PyPI pip package

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopop#105]
And conda package?

**Update [@leewujung 2023/12/08]**:
- We've decided to create a pypi package
- Probably also a good idea to create a conda package

**Comment by leewujung** [comment]
From Sept 29 notes we decided to create a PyPI package.

I propose that we change the package name to `echobiome` so that it is more descriptive of what the package is for.

**Comment by leewujung** [comment]
The name change is now tracked in #144. I'll remove the "?" in the issue title since we've decided to do this.

**Comment by brandynlucca** [comment]
This was included as part of PR #241 and can now be closed.
