### ISSUE TITLE
Determine API changes to allow multi-species processing

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#110]
To expand the package to handle krill inversion, we need to review the current API and determine changes needed for this expansion. We should make the design flexible so that future expansion to include other species is straightforward. Below are the specifics, which we'll continue to add to in the next few weeks:

### Tasks
- Determine modifications needed in the data loading functions to utilize the new YAML structure that accommodates multiple species
- Determine subpackage structure for flexible expansion to krill and other potential future species

**Comment by brandynlucca** [comment]
This has been encapsulated within #289 and can therefore be closed.
