### ISSUE TITLE
Add documentation of export "report" files to Jupyter Book

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopop#112]
Add a page to the Jupyter Book documenting the input files in detail

- Note: All Google links below have restricted access.
- 15 files are exported as Excel "reports": 
  - kriging_based_aged_output_all.xlsx
  - kriging_based_aged_output_non_zero.xlsx
  - kriging_based_core_output_all.xlsx
  - kriging_based_core_output_non_zero.xlsx
  - kriging_based_len_age_abundance.xlsx
  - kriging_based_len_age_biomass.xlsx
  - kriging_input.xlsx
  - specimen_length_counts_haul.xlsx
  - total_length_counts_haul.xlsx
  - transect_based_aged_output_all.xlsx
  - transect_based_aged_output_non_zero.xlsx
  - transect_based_core_output_all.xlsx
  - transect_based_core_output_non_zero.xlsx
  - transect_based_len_age_abundance.xlsx
  - transect_based_len_age_biomass.xlsx
- The file names are currently hardwired in [reports.py::create_and_write_reports](https://github.com/uw-echospace/EchoPro/blob/33d64fc67be3182e0a28da6be5ca54cb1cca944e/EchoPro/reports.py#L824)
- The [Output file descriptions - UW Google doc](https://docs.google.com/document/d/1H6DTssJV4JZ-fcAnLxlMP32pE3jIVBPe/edit) is annotated version of a document originally from Chu ([Output file descriptions](https://docs.google.com/document/d/1X41jeHdgnWTo7j5qKWU9Uu2ALou0y7Eu/edit)) that describes each report file.
- The [EchoPro Output Report Files Google doc](https://docs.google.com/document/d/1jheDlAZgn7u9lcKC7gaEGNepGVEBsfUF6KGdSZX1JdE/edit#heading=h.su2pr9x24ut5) contains notes from a meeting in January 2023 where we went over all the output files.
- The Google Drive folder [EchoPro_matlab_output_brandon_age_22_end_bin](https://drive.google.com/drive/folders/1_sUDUJY_e6M9cB3n5uibWeoukPqFP8ZO?usp=drive_link) contains the set of 2019 Excel report files generated by Matlab EchoPro.

Other relevant issues:
- #92

**Comment by emiliom** [comment]
File name match up between Python EchoPro and Matlab EchoPro (2019) report files:

Python EchoPro | Matlab EchoPro
---- | ----
kriging_based_aged_output_all.xlsx | EchoPro_kriged_aged_output-2019_0.xlsx
kriging_based_aged_output_non_zero.xlsx | EchoPro_kriged_aged_output-2019_1.xlsx
kriging_based_core_output_all.xlsx | EchoPro_kriged_output-26-Jan-2023_0.xlsx
kriging_based_core_output_non_zero.xlsx | EchoPro_kriged_output-26-Jan-2023_1.xlsx
kriging_based_len_age_abundance.xlsx | kriged_len_age_abundance_table.xlsx
kriging_based_len_age_biomass.xlsx | kriged_len_age_biomass_table.xlsx
kriging_input.xlsx | kriging_input.xlsx
specimen_length_counts_haul.xlsx | aged_len_haul_counts_table.xlsx
total_length_counts_haul.xlsx | total_len_haul_counts_table.xlsx
transect_based_aged_output_all.xlsx | EchoPro_un-kriged_aged_output-2019_0.xlsx
transect_based_aged_output_non_zero.xlsx | EchoPro_un-kriged_aged_output-2019_1.xlsx
transect_based_core_output_all.xlsx | EchoPro_un-kriged_output-26-Jan-2023_0.xlsx
transect_based_core_output_non_zero.xlsx | EchoPro_un-kriged_output-26-Jan-2023_1.xlsx
transect_based_len_age_abundance.xlsx | un-kriged_len_age_abundance_table.xlsx
transect_based_len_age_biomass.xlsx | un-kriged_len_age_biomass_table.xlsx

**Comment by emiliom** [comment]
I'll create an initial, slim version of this page by Saturday.

**Comment by brandynlucca** [comment]
This has been encapsulated within #290 and can therefore be closed.
