### ISSUE TITLE
Create a config file validator

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#125]
Right now the config files are just read as is and the only check is checking the file existence. It will be good to have a validator to check the content of the file.

This came from a TODO in `_check_init_file`:
https://github.com/uw-echospace/EchoPro/blob/b8314f13b812272738a10344034f3c19977baf90/EchoPro/survey.py#L114-L116

and a similar TODO in `_check_survey_year_file`:
https://github.com/uw-echospace/EchoPro/blob/b8314f13b812272738a10344034f3c19977baf90/EchoPro/survey.py#L138-L140

Below from #13:
> - The configuration files have all necessary variables defined and these values are of the correct type. Here we could also check that the paths provided exist.

**Comment by brandynlucca** [comment]
The second `TODO` item has been addressed:

https://github.com/OSOceanAcoustics/echopop/blob/f244105852a86a7ea0fa887401321b39106e5c90/echopop/utils/data_file_validation.py#L5-L66

The first `TODO` item remains at-large.
