### ISSUE TITLE
Implement processing of all-age data

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#129]
- currently only the option `exclude_age1=True` is implemented
- did Chu implement the option to include all ages?
- consider changing the option name to allow selecting adult and/or age-1

See #91 for some previous info from @b-reyes.

@emiliom : Do you know if all-age processing was implemented in Matlab? (this is why I "assigned" this to you, not to ask you to implement the functions).

**Comment by rebeccathomas-NOAA** [comment]
I know we absolutely need processing of age-1 data, but I'm not exactly sure what kind of processing Chu was doing with the age-1 in his latest version.   I know his code produces different numbers with age-1 =TRUE and not true.  I also know Chu was working on a few different implementations of age-1, and I'm not sure what is in his latest code.

**Comment by leewujung** [comment]
Notes from 2024/01/29 meeting:

**Age binning:** 
- include age-1 in strata, but kick them out before kriging
- should not include age-0
- current estimate is age-2 only, trying to move to include age-1
- age-1 has very different net selectivity


**Temp decision:**
- age-0 and age-1 should be in their own bins
- so have age-0 / age-1 / age-2+
- But what do we include for the total number of fish? TBD

@brandynlucca -- could you comment on what the implemented handling is at the moment and point to the code section? to help us get back to this context quickly when we circle back to this, in the hopefully not very distant future!

**Comment by leewujung** [comment]
This issue is now resolved. In the 2024/01/29 meeting we also discussed this along with the bug in #42.

**Comment by leewujung** [comment]
I accidentally closed the wrong issue! Re-opening this.

**Comment by brandynlucca** [comment]
The argument `exclude_age1` has been added to `transect_analysis(...)` that selects the correct NASC data source depending on if `exclude_age1 = True` (i.e. adult-only while accounting for leaked age-1 contributions) and `exclude_age1 = False` (i.e. everything gets accounted for). This argument then propagates into other parts of the analysis without requiring any additional input (i.e. `stratified_analysis(...)` and `kriging_analysis(...)`). 

The apportionment step is independent of this decision and is determined based on the original biological data. The primary change induced by `exclude_age1` is 1) which NASC data to use and 2) whether kriged population estimates (e.g. biomass) apportioned by age and length need to be further reapportioned to remove contributions of age-1 fish. 

This can be closed once PR #241 is merged.
