### ISSUE TITLE
Identify a collection of desired output plots

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#145]
This [google doc](https://docs.google.com/document/d/1f-Ifmn7q5C58YVVX7NP90HUpE-qZWW4wFVkBZCOoOuM/edit#heading=h.g15ni3iqleip) includes a collection of plots generated by Matlab EchoPro. Some plots have wrong axis labels, but those are easy to correct.

This issue to track discussions for what outputs we want for the python version.

**Comment by rebeccathomas-NOAA** [comment]
Do you have any thoughts for how best to "id" plots?  I know I have some plots in mind to absolutely have, but I'm not really sure how to refer to them.

**Comment by leewujung** [comment]
Here's the link to the recording (restricted access) for the meeting where @rebeccathomas-NOAA walks through and discusses the figures she uses in Matlab EchoPro: 

The key highlights are:
- There are a few plots that got generated in the beginning that is related to Echoview NASC exports that we need to produce, since it is useful for debugging the input files
- The interactive capability with kriging outputs on the map has been implemented, just need:
  - updating for new data structure
  - making sure things run in clean environment
- The combination of plots that basically extract and plot data from the "result dataframes" (either based on transect results or kriging outputs) can be easily produced once the codebase overhaul is completed. We will:
  - make a documentation showing what is in which result dataframes
  - the documentation will also include how to produce useful plots
  - the docs will use Jupyter notebooks, so that the cells are directly executable and reproducible, so it would be easy to modify for working with data from another year
  - add jupyter notebooks that shows how to plot

@rebeccathomas-NOAA @brandynlucca : the above are what I remembered from our 2024/01/29 meeting. Feel free to make any corrections or additions!

**Comment by brandynlucca** [comment]
This has been encapsulated within #290 and can therefore be closed.
