### ISSUE TITLE
Ingest Echoview exports to NASC input files

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#158]
The NASC input files to EchoPro are "pre-processed" from the Echoview exports, through [construct_NASC_int_file_new.m](https://github.com/uw-echospace/EchoPro_matlab/blob/eb6ac07d48f13c8ebd173b0072f67015bcacf205/general/processing/construct_NASC_int_file_new.m) that is called in [general/processing/generate_EV_EI_NASC_table.m](https://github.com/uw-echospace/EchoPro_matlab/blob/main/general/processing/generate_EV_EI_NASC_table.m).

This data ingestion has not been implemented and is critical for processing multiple year's of data, so we need to add it ASAP.

**Comment by leewujung** [comment]
@rebeccathomas-NOAA has an update for herring recently and she will upload to the [EchoPro Matlab repo](https://github.com/uw-echospace/EchoPro_matlab).

**Comment by rebeccathomas-NOAA** [comment]
I tried to upload the file, but it says I don't have push permissions.

**Comment by leewujung** [comment]
Oops sorry, could you please just email me the file?

**Comment by rebeccathomas-NOAA** [comment]
Yup, just did!
