### ISSUE TITLE
Mean sex-specific weight estimate discrepancy

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#165]
Small differences in the resulting sex-specific mean weights that are calculated for each stratum, particularly in cases where a significant proportion of the overall biological datasets comprise unsexed fish.

**Comment by leewujung** [comment]
Adding more info for tracking: 

From https://github.com/uw-echospace/EchoPro/pull/164#discussion_r1465624381:
> The discrepancy between the original code and how this is summed here. This seems to be how the stratum sample size was calculated; the original code expressly omits values where `sex = 3` from the `specimen` dataset. There was a TODO comment included in there that just used the full sum of both the `length` and `specimen` dataframes for that calculation.
> 
> For the most part, these differences were non-existence where `sex=3` was a trivial fraction of the data. When `stratum=2`, this is where the largest differences are/were observed, which coincides with a non-trivial number of unsexed animals where both the male and female samples comprise ~ 25% of the overall sample (i.e. ~ 50% of the sample from both datasets were sexed). So while the proportions for both `male` and `female` are identical between the original and updated code, the mean weights are slightly different.

**Comment by brandynlucca** [comment]
This has been determined to result from a bug in the original MATLAB code where unsexed fish were included when calculating the female-specific length-weight regressions. This does not occur in the current `echopop` implementation.

This can be closed once PR #241 is closed.
