### ISSUE TITLE
Implement new `Survey` object data structure along the processing chain

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#169]
This came from https://github.com/uw-echospace/EchoPro/pull/164#pullrequestreview-1822245369 and https://github.com/uw-echospace/EchoPro/pull/164#issuecomment-1894700162.

We will review and settle down the `Survey` object data structure once the kriging functions are refactored, then we can release v0.4.0!

**Comment by leewujung** [comment]
@leewujung and @brandynlucca have reviewed and agreed on a new data structure, now documented as a figure in the [Core data structure page](https://echopop.readthedocs.io/en/latest/core_data_structure.html).

I changed the title of this issue to be implementing these changes.

**Comment by brandynlucca** [comment]
A new core data structure has been implemented to streamline the processing workflow: 
`Survey.config` -> `Survey.input` (+ `Survey.config`) -> `Survey.analysis` -> `Survey.results`

This can therefore be closed once PR #241 is merged.
