### ISSUE TITLE
Add unit tests for data loader functions

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#170]
As the name suggests. We'll take the mock data approach for unit tests.

**Comment by brandynlucca** [comment]
Integration tests for both the configuration and data file loaders have been implemented which both used mocked datasets (PR #195).

**Comment by leewujung** [comment]
The data loader test from #173 is not complete (see comment in `test_data_loader`), so I'll re-open this.

**Comment by brandynlucca** [comment]
This has been resolved in PR #221 and can therefore be closed pending future changes to additional data formats (e.g. NASC data files, related to #158).
