### ISSUE TITLE
Add unit tests to transect analysis  functions

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#171]
We'll use the mock data approach here, so that we can spin up a simple CI mechanisms for future PRs.

This will go hand-in-hand with refactoring `Survey` class methods in #203, and make sure the implementation corresponds to the mathematical operations in the docs.

**Comment by brandynlucca** [comment]
This is in conjunction with PR#221.

**Comment by brandynlucca** [comment]
This has been resolved in PR #221 and can therefore be closed.
