### ISSUE TITLE
Failed integration tests for various `Echopro` functions and methods

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#177]
https://github.com/uw-echospace/EchoPro/blob/f79b6d5bba66ed731b8c414cba01b89230c116e5/EchoPro/tests/test_data_loader.py#L22

The CI test fails due to `load_configuration` being converted from a class method to a standalone function (as discussed in PR #176). This is an expected failure since `load_configuration` should be called via `load_configuration(...)` rather than `Survey.load_configuration(...)`. This is currently limited to the test for this specific function, but this issue will be used to denote other failed integration tests as testing functions are incorporated into `Echopro`. The list below will serve as a tracking list that will be periodically updated as additional failed tests are discovered as well as errors that are fixed below.

_Current failed tests_
- [ ] `load_configuration`

**Comment by leewujung** [comment]
I believe this issue is resolved.
