### ISSUE TITLE
Improving functions and methods for importing INPFC strata definitions

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#178]
https://github.com/uw-echospace/EchoPro/blob/8e0080cfdf12e0f9b288bf43925d9fa30f0e71e4/EchoPro/survey.py#L264

A rough implementation of the `INPFC` strata definitions that are found within the same `.xlsx` file as the data for parameterizing `geo_strata` was incorporated into PR #176. This implementation _works_, but it required a few changes to be made to other `Survey`-class methods and other supporting functions (e.g. `load_configuration(...)`; see Commit [1afeea6](1afeea677bb9a9777940082092435ee6fb81af3f) for more details). This also adds a slightly updated formatting change to the  `survey_year_****_config.yml` configuration file whereby the `geo_strata` file includes a single filename, but then comprises `sheetname: [INPFC, stratification]` instead of just `sheetname = stratification`. 

The motivation for this change was to avoid hard-coding (and therefore burying) the INPFC latitudinal limits in the code in case changes need to be made in the future and to provide more control to end-users.

**Comment by leewujung** [comment]
This is related to https://github.com/OSOceanAcoustics/echopop/issues/38#issuecomment-2052371255 and #181.

**Comment by brandynlucca** [comment]
The INPFC-specific `xlsx` sheet has been added to the `survey_year_****_config.yml` configuration file format and is appended alongside the KS strata to the relevant dataframes contained within the `Survey`-class attributes. This can therefore be closed once  PR #241 is merged.
