### ISSUE TITLE
Create functionality to generate reports (tabular data exports)

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#18]
In the Matlab version of EchoPro, the user can generate reports -- tabular data exports in Excel format. This capability is being implemented based on current Matlab functionality and input from the FEAT team.

*(@emiliom edited this text on 1/30/23 to reflect current focus)*

**Comment by emiliom** [comment]
Here is a list of the 15 Excel report files now being generated:
- kriging_based_aged_output_all.xlsx
- kriging_based_aged_output_non_zero.xlsx
- kriging_based_core_output_all.xlsx
- kriging_based_core_output_non_zero.xlsx
- kriging_based_len_age_abundance.xlsx
- kriging_based_len_age_biomass.xlsx
- kriging_input.xlsx
- specimen_length_counts_haul.xlsx
- total_length_counts_haul.xlsx
- transect_based_aged_output_all.xlsx
- transect_based_aged_output_non_zero.xlsx
- transect_based_core_output_all.xlsx
- transect_based_core_output_non_zero.xlsx
- transect_based_len_age_abundance.xlsx
- transect_based_len_age_biomass.xlsx
