### ISSUE TITLE
Add argument for stratifying calculations using KS or INPFC stratum levels

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#181]
This is a point referenced in PR #176. It may be worth including an argument in `stratified_transect_statistic(...)` that flags the use of either `INPFC` or `KS` for the stratum-level grouped calculations.

_Originally posted by @leewujung in https://github.com/uw-echospace/EchoPro/pull/176#pullrequestreview-1877781915_

**Comment by leewujung** [comment]
This is related to discussions here: https://github.com/OSOceanAcoustics/echopop/issues/38#issuecomment-2052371255

**Comment by brandynlucca** [comment]
A `stratum` argument has been added in PR #241 to the three current `Survey`-class analysis methods (`transect_analysis`, `stratified_analysis`, and `kriging_analysis`) that enables either `ks` or `inpfc`. However, the full implementation using `ks` is not yet included for `stratified_analysis(...)`, although it is unlikely that `ks` makes sense as a stratum option for the Jolly and Hampton (1990) algorithm. I will confirm this by reading through the `EchoPro` implementation once more -- if it is the case that `ks` is not applicable to `stratified_analysis(...)`, then this issue can be closed once #241 is merged.
