### ISSUE TITLE
Change how unsexed and sexed fish are included for biomass apportionment

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#183]
When calculating the sex proportions of fish from stations 1 and 2, the current `main` branch sums the sexed (i.e. `male` and `female`) fish from station 2 and **all** fish from station 1 (i.e. `male`, `female`, and `unsexed`). 

https://github.com/uw-echospace/EchoPro/blob/93f0dcfea5cab6949c7d110eb0016014fbbcfcd0/EchoPro/computation/transect_results.py#L420-L426

This implementation did not seem to be correct. However, there were some ambiguities in the Matlab source code that made discerning the correct implementation difficult. After meeting with Chu, we have gained some clarity on both the Matlab implementation as well as the intention/rationale behind the calculation. Consequently, the [updated working branch](https://github.com/uw-echospace/EchoPro/tree/brandynlucca-kriging) implementation may be incorrect.

https://github.com/uw-echospace/EchoPro/blob/2157de885498f6b6d951ccee85ed7a6dfb8818ba/EchoPro/survey.py#L646-L652

Notably, the intent of this processing is to: 

1. Calculate male-to-female ratio
2. Calculate the sexed-to-unsexed ratio
3. Sum the total biomass across indices (e.g. `stratum_num`)
4. Apply male-to-female sex ratio to the total unsexed biomass
5. Apportion the total sexed biomass into `male` and `female`

Therefore, changes are likely required for the initial sex proportion calculations:

https://github.com/uw-echospace/EchoPro/blob/2157de885498f6b6d951ccee85ed7a6dfb8818ba/EchoPro/survey.py#L591-L764

This then may necessitate changes in how the sexed and unsexed proportioned biomasses are calculated: 

https://github.com/uw-echospace/EchoPro/blob/2157de885498f6b6d951ccee85ed7a6dfb8818ba/EchoPro/survey.py#L870-L1007

Lastly, the appropriate documentation explaining both the scientific rationale/context and mathematical equations (i.e. within the related ReadTheDocs) will provide clarity on what the software is specifically doing at this step.

**Comment by leewujung** [comment]
I think after the last couple weeks we've resolved this issue fully with the new doc page on biomass apportioning.

@brandynlucca : let me know if you think we should keep this open for any reason. I think we should treat abundance apportioning as a separate issue, since it's tracked in #217.

**Comment by brandynlucca** [comment]
@leewujung: I need to comb through the transect analysis portion of the code to make a few adjustments (and validate) toward how unsexed fish are handled. This is a parallel issue, I suppose, with both the transect analysis _and_ kriging apportionment. Now that we have a better grasp of the intent and calculations, this should be a pretty quick read-through and change that I can incorporate into a separate PR.

**Comment by leewujung** [comment]
Sounds good. Thanks!

**Comment by brandynlucca** [comment]
As [discussed](https://github.com/OSOceanAcoustics/echopop/pull/215#discussion_r1561878197) with PR #215, documentation is needed to make it clear where unsexed fish are relevant (e.g. calculating the length-weight regressions).

**Comment by brandynlucca** [comment]
The main thinking behind this issue can be attributed to some confusion arising from how the `EchoPro` code was originally written and trying to identify why average weights per stratum (for each sex and overall) and length/age bins were difference between `EchoPro` and `echopop`. 

After discussions with FEAT and the updated implementation in PR #241, the treatment of male/female/unsexed fish from both stations (1: unaged; 2: aged) has been updated to match the original `EchoPro` code concerning the calculation of the normalized weight fractions. The result is that the sex-specific `echopop` average stratum weights (and average weights per length and age bin) are not identical to those from `EchoPro` due to differences in how the length-weight regressions are derived for each sex. In `EchoPro`, unsexed fish are included alongside females for the female-specific length-weight linear relationship while only males are included for the male-specific relationship. The `echopop` implementation does not include unsexed fish when fitting the length-weight regressions for male and female fish. 

This can be closed once PR #241 is closed.
