### ISSUE TITLE
"Biological" input data generation

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#196]
We need to clarify which input files are generated by whom.

From March 4 meeting, the consensus was:
- Biological: Alicia
- NASC Exports: RT 
  - though need the `Stratification/transect_haul_...` file generated by EchoPro matlab code to assemble this
  - this is an unfinished task tracked in #158 
- Kriging: all files are "inherited" from previous years, but they could change
- Stratification: RT

The task here is follow up with Alicia on:
- if there are scripts in place to pull all variables directly from the database and form these biological input files, or is this one of the TODO items from our side
- if all the biological variable names have been agreed on from previous work with Emilio

**Comment by brandynlucca** [comment]
@leewujung I believe this can probably be closed since we have gotten confirmation on where files come from, which ones are generated by the FEAT group, etc. I'll bring this up when we meet.
