### ISSUE TITLE
Reduce the number of `Survey`-class methods

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#203]
A variety of `Survey`-class methods can be rewritten such that they can be imported as external functions. This will further help code legibility and reduce the length (i.e. number of rows) of `survey.py`. 

- [x] `impute_missing_sigma_bs`
- [x] `fit_binned_length_weight_relationship`
- [x] `apportion_kriged_biomass`
- [x] `biometric_distributions` (large portions of it can be refactored into an external function)
- [x] `nasc_to_biomass_conversion` (large portions of it can be refactored into an external function)
- [x] `strata_age_binned_weight_proportions` (large portions of it can be refactored into an external function)
- [x] `strata_sex_weight_proportions` (large portions of it can be refactored into an external function)

**Comment by leewujung** [comment]
Tracking another few from PR https://github.com/OSOceanAcoustics/echopop/pull/204#pullrequestreview-1925864948.

**Comment by brandynlucca** [comment]
These suggested functions have been refactored even further in PR #241 and have all been relocated outside of `echopop.survey` to a separate module (`echopop.analysis`) that provides general orchestrated workflows for `Survey`-class methods. This therefore makes the code specific to `echopop.survey` easier to read, follow, and debug. Therefore, this can be closed once PR #241 is merged.
