### ISSUE TITLE
Questions concerning back-calculated abundance apportionment

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#224]
When back-calculating abundance from the apportioned kriged biomass, it is unclear whether the unaged abundance estimates should be redistributed over the age-bins similar to biomass.

**Comment by leewujung** [comment]
From meeting with @rebeccathomas-NOAA and @ElizabethMPhillips on 2024/04/16:

For abundance derived from kriged biomass, in the reporting:
- Need global aged and unaged abundance, that is not spatially explicit
- Also need spatially explicit aged + unaged but proportioned to aged summed together

**Comment by leewujung** [comment]
Some additional digging around in the [matlab code](https://github.com/uw-echospace/EchoPro_matlab):
- These lines get the aged and unaged abundance calculated:
  In get_kriged_biomass.m
  https://github.com/uw-echospace/EchoPro_matlab/blob/main/general/processing/biomass/get_kriged_biomass.m#L342-L352
  No apportioning afterwards to apply the aged proportion to the unaged samples.

- The data matrix is then saved to a different variable name: `kriged_Num_Len_Age_Matrix_AcoustM`/`kriged_Num_Len_Age_Matrix_AcoustF`
   https://github.com/uw-echospace/EchoPro_matlab/blob/main/general/processing/biomass/get_kriged_biomass.m#L392-L396

- Then in generate_report.m these variables are used to written to the excel files
   https://github.com/uw-echospace/EchoPro_matlab/blob/main/general/report/generate_reports.m#L106-L116

**Comment by leewujung** [comment]
Check https://github.com/OSOceanAcoustics/echopop/issues/219#issuecomment-2053863594 for related discussion, for the google slide with flow diagram.

**Comment by rebeccathomas-NOAA** [comment]
As an FYI, I was investigating some weird abundance results in the full age estimates (age1+ method), and I am pretty sure that the abundance reports are not correct for the age-2+ total number (when age-1's are being included)
If you look at lines
https://github.com/uw-echospace/EchoPro_matlab/blob/553b46b6a8a4c0dae6831727ef9a59a6a0f97b57/general/report/generate_reports.m#L169C1-L170C138
note that the age-2+ total sums _all_ the unaged fish into the age-2+ total, without the age-'1s being apportioned out of the unaged fish.
However, this doesn't throw into question the main matrix, so it is probably a relatively small detail except that these are the exact numbers stock assessors might use in an age-1+ estimate, so I wanted to flag it in case it shows up in EchoPop.
