### ISSUE TITLE
Obtain a fresh copy of newly queried 2017 input files

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#234]
This issue is to keep track of the action item from #155:
> Once the current code refactoring is done (v0.4.2), ask Alicia for fresh (newly queried) 2017 files

The goal is to make sure the variable names exported from the NWFSC database works seamlessly with what Echopop expects in terms of input variables in the excel sheet.

**Comment by brandynlucca** [comment]
This is related to #307. Internal testing demonstrates compatibility with the 2017 dataset with some modifications. This will be closed since this is also represented in #307.
