### ISSUE TITLE
Weights from some hauls are zeroed out after ingestion

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#235]
The weights from some hauls are mysteriously zeroed out in the Matlab EchoPro code. It is unclear why that is that case:
- all seem to be hauls that have small weights (but NOT stratum 0)
- these are NOT 2019-specific (though for 2013 there was specific treatment)

**Comment by brandynlucca** [comment]
This is linked to cases where no length measurements were made specifically for **Station 1 (i.e. unaged)** fish 
 ([get_historical_strata_data.m#L395-396](https://github.com/uw-echospace/EchoPro_matlab/blob/553b46b6a8a4c0dae6831727ef9a59a6a0f97b57/general/load_files_parameters/get_historical_strata_data.m#L395-L396)). Typically, the total weights from both stations are pooled together to calculate the variable `total_wgt` needed for computing the length-age-sex weight proportions ([get_historical_strata_data.m#L655-L666](https://github.com/uw-echospace/EchoPro_matlab/blob/553b46b6a8a4c0dae6831727ef9a59a6a0f97b57/general/load_files_parameters/get_historical_strata_data.m#L655-L666)). For cases where length measurements from both stations are collected, the sum of weights from each station are not equal. For the cases where length measurements are missing from Station 1, the sum of weights from Station 2 is close to, but still less than, the summed Station 1 weight.
 
**Question:** when Station 1 lengths are absent, do the summed Station 2 weights represent the full catch weight for each haul?

**Comment by brandynlucca** [comment]
This has been addressed/resolved since haul weights are set to 0.0 when the number of fish was less than 50 for any particular haul.
