### ISSUE TITLE
NASC ingestion reapportioning from raw data

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#237]
- There is reapportioning / separation of age-1 from age-2+
- This is done based on `Len_Age_key_ALLn`
- The values used are from the `_Age2+` spreadsheet, but not clear why the reapportioning (to remove age-1) happens

Is this intentional regarding the region types in Echoview selected to be exported?

**Comment by brandynlucca** [comment]
This is linked to RT's [comment](https://github.com/OSOceanAcoustics/echopop/issues/229#issuecomment-2093332864) in #229. This was primarily a GUI-specific issue related to my local environment rather than the software itself (similar to #236).
