### ISSUE TITLE
Determine method name for mesh cropping

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#243]
Right now the default `crop_method` for the kriging analysis is called `interpolation` since it replicates the survey extent interpolation steps used in `EchoPro`. However, this name may not be particularly helpful or informative and thus should be assigned a better name.

**Comment by leewujung** [comment]
How about `crop_method="transect_ends"` ? That is what this is doing?

**Comment by brandynlucca** [comment]
This was addressed via #269 and can therefore be closed.
