### ISSUE TITLE
Ensuring biological data column names match those in expected data files

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#261]
It seems that the files used for designing this version of `echopop` have entirely different column names than those generated by NWFSC. There is also some inconsistency in the spreadsheet column naming (and number of columns) across years. This needs to be amended since the data will otherwise be unreadable and yield an Error when trying to initialize the `Survey`-class object.

**Comment by leewujung** [comment]
Do you mean the files that you have been working with and the files generated from the ship? 

I guess I am not sure what are "the files used for designing this version of echopop" vs "those generated by NWFSC" - since both are from NWFSC?

**Comment by brandynlucca** [comment]
This refers to the `*.xlsx` biological files used for post-processing. The `*.xlsx` files I have been using to develop the package have different column names than the actual files FEAT has used in the past for `EchoPro`.

**Comment by leewujung** [comment]
Interesting. I wonder how that occurred. I know Emilio manually changed some column names, and at least some of the changes were recorded, but perhaps some were not.

**Comment by rebeccathomas-NOAA** [comment]
I've got an e-mail out to Alicia about current database capabilities; I haven't heard back yet.  In the meantime, I went through the biodata files and tried each one to see which ones had column naming issues.
  biodata_catch: columns expected but not found: ['haul_weight', 'species_id', 'haul_num']
  biodata_gear: fine
  biodata_haul:fine
  biodata_length: columns expected but not found: ['species_id', 'sex', 'haul_num', 'length_count', 'length'] 
  biodata_specimen_ages: Missing columns in the Excel file ['sex', 'species_id', 'haul_num', 'weight', 'age', 'length']

**Comment by brandynlucca** [comment]
This has been addressed in #268 and can therefore be closed.
