### ISSUE TITLE
Bugs in computing sex proportion and length distribution of fish

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#42]
To compute the biomass density several constants need to be created. It appears that some of these constants are not correctly created. Specifically, the following should be reviewed: 
- Several proportions and fractions are created in the function [_compute_proportions](https://github.com/uw-echospace/EchoPro/blob/47568e4a96ad74ac1c15167b0e314c8407a09ad3/EchoPro/compute_biomass_density/compute_biomass_density.py#L366-L368) and some of them do not appear to be correct
   - All values that should be investigated are marked with `TODO`
- In the function [_fill_len_wgt_prod](https://github.com/uw-echospace/EchoPro/blob/47568e4a96ad74ac1c15167b0e314c8407a09ad3/EchoPro/compute_biomass_density/compute_biomass_density.py#L491-L492) we are attempting to obtain the length key for station 2 for all fish. However, in the Matlab code (and as a result in the Python code) we exclude the unsexed fish. 
- The function [_get_age2_wgt_prop](https://github.com/uw-echospace/EchoPro/blob/47568e4a96ad74ac1c15167b0e314c8407a09ad3/EchoPro/compute_biomass_density/compute_biomass_density.py#L674-L683) computes the age 2 weight proportion using the specimen data. However, there is a deliberate dropping of NA values that only occurs in this calculation. We should make it so that this is done when the data is first loaded and then use this data for all calculations. 

**@leewujung update [2023/12/05]**:
- `_fill_len_wgt_prod` is now called `_fill_averaged_weight`
- `_get_age2_wgt_prop` is now called `_get_all_age_weight_proportions`
- now sure what age 2 above means -- probably just "adult"

**Comment by leewujung** [comment]
The latest status where `_get_distribution_lengths_station_2` should be corrected:
https://github.com/uw-echospace/EchoPro/blob/2c832292cb9cbae0b5bfd07c0b1ef328043d94c2/EchoPro/computation/transect_results.py#L529-L535

**Comment by leewujung** [comment]
Closing this now that we have traced the matlab code to understand all details and implemented a clean version of python code.
