### ISSUE TITLE
Review Least Squares fit of semi-variogram

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#55]
Currently there is a slight difference in the Least Squares fit of the semi-variogram between the Matlab and Python code. This causes differences in the semi-variogram model parameters produced and thus causes a slight difference in the Kriged biomass estimate. 

In short, the Matlab code performs the fitting by forcing the nugget to be exactly zero. This often results in a kink in the graph around the nugget. This is shown in the Matlab produced fit below (where the black circle brings your attention to the kink in the graph):

![Screen Shot 2022-12-08 at 2 38 04 PM](https://user-images.githubusercontent.com/53541061/206582649-e5f7aec1-a159-4fa3-9583-fd41a1d25ca5.png)

In the Python version of the code we bound the nugget to be close to zero, but do not force it to be exactly zero. This produces the smoother fit as shown below:

![Screen Shot 2022-12-08 at 2 42 26 PM](https://user-images.githubusercontent.com/53541061/206582956-94c56190-c967-4d85-a90d-01709f41c646.png)

We need to decide which method is more appropriate.

**Comment by leewujung** [comment]
@brandynlucca : FYI, since you're now working on kriging section.
