### ISSUE TITLE
Implement ahead-of-time compilation

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#7]
In EchoPro we create several JiT functions with Numba, see [numba_modules.py](https://github.com/uw-echospace/EchoPro/blob/master/EchoPro/numba_modules.py). Although these functions do provide a significant improvement in speed, they are JiT functions. Thus, there is some overhead associated with their initial calls. One can "remove" this overhead by implementing [ahead-of-time](https://numba.pydata.org/numba-doc/dev/user/pycc.html) compilation.

**Comment by leewujung** [comment]
I'll close this now since it is not clear if we really needs this. We can look into efficiency when speed does become a bottleneck.
