### ISSUE TITLE
Non-uniform binning methods

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#71]
While constructing parameters needed to create variable values over the mesh points (PR #70) it was found that a different binning method was used for the length and age data. This is in comparison to the binning method used in the `ComputeTransectVariables` class. Specifically, 

- `ComputeTransectVariables` class binning method
    - Within this class distributions are constructed by binning age and length data using the same method. The binning method `_get_bin_ind` is used and it creates a distribution by computing a histogram using bins that are centered. This binning method is more consistent with a traditional binning method. 
-  `ComputeKrigingVariables` class binning method
    - Within this class the length and age data are binned differently!
        - The lengths are binned using bin edges, rather than bin centers. It should be noted that this method and the one in `ComputeTransectVariables` use the same array to define bin edges and bin centers.
        - The ages are binned using a strict equality, rather than between a range. Again, it should be noted that this method and the one in `ComputeTransectVariables` use the same array to define the bins.

Since the binning methods vary between `ComputeTransectVariables` and `ComputeKrigingVariables`, it may not be appropriate to compare the variables created for different ages and genders. To make this comparison, it may be necessary to change the binning methods in `ComputeKrigingVariables` so they align with the one used in `ComputeTransectVariables`.

**Comment by leewujung** [comment]
@brandynlucca : Pinging you on this issue just so that you're aware, since you're wading through the kriging code at the moment.

**Comment by leewujung** [comment]
@brandynlucca's new implementation has gone through all steps for kriged biomass apportioning and what's documented here does not appear to be problems needing to be addressed. Therefore, we will close this now.
