### ISSUE TITLE
Difference in age bins between Chu's Matlab code and the updated Matlab code

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#73]
In Chu's original Matlab code age bins were defined as ages 1 through 20 (with step size 1). However, a while ago it was found and confirmed by Chu that these age bins can miss out on older animals. It turns out that this is the case for the 2019 survey. For this reason, in the current Matlab code and also the current Python code we are defining the age bins as ages 1 through 22 (with step size 1). This allows us to capture all of the data. 

For future reference, it should be noted that this will change the output (such as biomass) slightly. Additionally, it should be noted that the Matlab code produces length-age distributed data for the reports by hard coding the age bins. Thus, the updated Matlab code will be hard coded for age bins of 1 through 22.

**Comment by leewujung** [comment]
@brandynlucca : pinging you here since this is something related to the current #168.

**Comment by leewujung** [comment]
@brandynlucca : I think this is not an issue in your implementation, right? since now all age bins are included in the dataframes. If so, could you close this issue?
