### ISSUE TITLE
Investigate redistribution of age 1 and un-aged data

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#81]
In PR #78 we constructed the variables biomass and abundance at each length and age bin. In comment https://github.com/uw-echospace/EchoPro/pull/78#issuecomment-1414341625 and subsequent comments we highlight that there is a distribution of the age 1 bin data and the un-aged bin data when creating the Kriging based variables. This distribution is completed by the functions `_redistribute_age1_data` and `_redistribute_unaged_kriged_biomass` in `EchoPro/computation/length_age_variables.py`. It is not clear why these distributions need to take place and why they are not used on the Transect based data. For this reason, we should investigate to see if the distribution of data is necessary.

**Comment by leewujung** [comment]
I'll close this issue now that we will work with the completely refactored API, and with clear mathematical expression of the operations.
