### ISSUE TITLE
Investigate the need for `exclude_age1=False` input to `EchoPro.Survey`

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#91]
Currently we always have `exclude_age1=True` in the `EchoPro.Survey` initialization. It is unclear if this `exclude_age1=False` will ever be used. We need to connect with the FEAT team and see if `exclude_age1=False` will  be used and if it is, implement all code associated with this option.

**Comment by leewujung** [comment]
I'm going to close this now since we plan to use an age filter for age-related processing at a later time. Right now all-age and age2+ are implemented. We'll have to add processing for age-1 fish.
