### ISSUE TITLE
In tabular reports, should subtotals be implemented where present in Matlab EchoPro?

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopop#92]
For the len-age binned data reports that currently (Matlab EchoPro) include subtotal rows and columns plus other annotation rows, we did not implement such subtotals in the initial implementation of the generate-reports capability (PR #84). We discussed this feature in a meeting with the FEAT team in Jan. 2023 about the report files, but didn't come to a definitive conclusion.

For now, the Excel report files that are generated are simple tables with a single header row and no sub-totals or additional annotations. Some of those files contain 3 tabs (3 tables), though, for male/female/all sexes.

We'll revisit this in a future meeting.

**Update [@leewujung 2023/12/08]**: see #112 for:
- Links to the report files from 2019 data
- Meeting discussions for requirement for Python EchoPro
- Side-by-side comparison table between Matlab and Python EchoPro

**Comment by emiliom** [comment]
We haven't heard back as to whether adding these subtotals will be a requirement.

**Comment by rebeccathomas-NOAA** [comment]
The subtotals are used by stock assessment in their data links, so it would be an important aspect of the data summary reports to replicate.

**Comment by brandynlucca** [comment]
This has been encapsulated within #290 and can therefore be closed.
